"""
SARO — Persona Metrics Definitions
Each persona gets up to 5 metrics with purpose tooltips (FR-*-03 from spec).
Used by both the API and Streamlit UI for card rendering.
"""

PERSONA_METRICS = {
    "forecaster": [
        {
            "key": "forecast_accuracy",
            "label": "Forecast Accuracy",
            "value": "85%",
            "target": "85%",
            "tooltip": "Measures gap forecast precision vs. NIST benchmarks. Higher = fewer missed risks.",
            "icon": "target",
            "color": "#2563eb",
        },
        {
            "key": "gap_preempt_rate",
            "label": "Gap Preempt Rate",
            "value": "40%",
            "target": "50%",
            "tooltip": "Percentage of compliance gaps identified before they become violations.",
            "icon": "shield",
            "color": "#7c3aed",
        },
        {
            "key": "ci_width",
            "label": "Confidence Interval Width",
            "value": "±12%",
            "target": "<±15%",
            "tooltip": "Narrower CI = more precise Bayesian predictions. Target is sub-15%.",
            "icon": "activity",
            "color": "#0891b2",
        },
        {
            "key": "sim_runtime",
            "label": "Simulation Runtime",
            "value": "8.2s",
            "target": "<10s",
            "tooltip": "Average time for 6-12mo regulatory gap simulation. Must stay under 10s.",
            "icon": "clock",
            "color": "#059669",
        },
    ],
    "autopsier": [
        {
            "key": "alert_precision",
            "label": "Alert Precision",
            "value": "88%",
            "target": "85%",
            "tooltip": "True positive rate for compliance alerts. Higher = fewer false alarms.",
            "icon": "crosshair",
            "color": "#dc2626",
        },
        {
            "key": "false_positive_rate",
            "label": "False Positive Rate",
            "value": "4.2%",
            "target": "<5%",
            "tooltip": "Percentage of alerts that were incorrect. Lower = less noise for auditors.",
            "icon": "alert-triangle",
            "color": "#ea580c",
        },
        {
            "key": "mitigation_rate",
            "label": "Mitigation Rate",
            "value": "70%",
            "target": "70%",
            "tooltip": "Percentage of critical findings with active mitigation plans. 70% minimum for compliance.",
            "icon": "check-circle",
            "color": "#16a34a",
        },
        {
            "key": "evidence_chain_integrity",
            "label": "Evidence Chain Integrity",
            "value": "99.8%",
            "target": "99.5%",
            "tooltip": "Percentage of audit records with valid SHA256 hash chains (Epic 4 integration).",
            "icon": "link",
            "color": "#7c3aed",
        },
    ],
    "enabler": [
        {
            "key": "effort_days",
            "label": "Avg Effort Days",
            "value": "3.2",
            "target": "<5",
            "tooltip": "Average days to resolve a critical compliance finding via remediation workflow.",
            "icon": "calendar",
            "color": "#2563eb",
        },
        {
            "key": "impact_score",
            "label": "Impact Score",
            "value": "8.4/10",
            "target": ">7.5",
            "tooltip": "Weighted score of remediation effectiveness across risk categories.",
            "icon": "trending-up",
            "color": "#7c3aed",
        },
        {
            "key": "roi_savings",
            "label": "ROI Savings",
            "value": "$150K",
            "target": ">$100K",
            "tooltip": "Based on fine avoidance and reduced audit costs from automated remediation.",
            "icon": "dollar-sign",
            "color": "#059669",
        },
        {
            "key": "critical_reduction",
            "label": "Critical Findings Reduced",
            "value": "70%",
            "target": "70%",
            "tooltip": "Percentage reduction in critical-severity findings after remediation cycle.",
            "icon": "arrow-down",
            "color": "#dc2626",
        },
    ],
    "evangelist": [
        {
            "key": "nps_score",
            "label": "Trust NPS",
            "value": "78",
            "target": ">75",
            "tooltip": "Net Promoter Score from stakeholders on AI trust and ethics reporting.",
            "icon": "heart",
            "color": "#ec4899",
        },
        {
            "key": "compliance_score",
            "label": "Compliance Coverage",
            "value": "82%",
            "target": ">80%",
            "tooltip": "Percentage of applicable EU/ISO/NIST controls mapped and evidenced.",
            "icon": "shield",
            "color": "#2563eb",
        },
        {
            "key": "trust_uplift",
            "label": "Trust Uplift",
            "value": "70%",
            "target": ">65%",
            "tooltip": "Improvement in stakeholder confidence after deploying SARO ethics reports.",
            "icon": "trending-up",
            "color": "#16a34a",
        },
        {
            "key": "report_generation_time",
            "label": "Report Gen Time",
            "value": "4.1s",
            "target": "<5s",
            "tooltip": "Average time to generate a standards-aligned PDF report.",
            "icon": "file-text",
            "color": "#7c3aed",
        },
    ],
}
