"""
Remedy Tab — SARO Enterprise Audit Issue Tracker v2.2

Shows all failed / warned / flagged / triggered trace records for a selected
audit, grouped by gate. Operators can:
- Review each issue with full finding detail
- See HITL (human-in-the-loop) detection status
- Mark items as remediated with notes
- Track overall remediation progress
- Export remediation report as Markdown
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any

import requests
import streamlit as st

from frontend import styles

logger = logging.getLogger(__name__)
_API_BASE = os.environ.get("SARO_API_URL", "http://localhost:8000").rstrip("/")


def _headers(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


def _get(path: str, token: str) -> Any:
    resp = requests.get(f"{_API_BASE}{path}", headers=_headers(token), timeout=30)
    resp.raise_for_status()
    return resp.json()


def _post(path: str, token: str, json: dict) -> Any:
    resp = requests.post(f"{_API_BASE}{path}", headers=_headers(token), json=json, timeout=30)
    resp.raise_for_status()
    return resp.json()


def _effort_label(result: str) -> str:
    return {"fail": "HIGH", "flagged": "HIGH", "triggered": "MED", "warn": "LOW"}.get(result, "LOW")


def _severity_label(result: str) -> str:
    return {"fail": "CRITICAL", "flagged": "HIGH", "triggered": "HIGH", "warn": "MEDIUM"}.get(result, "LOW")


def _hitl_detected(trace: dict) -> bool:
    """Heuristic: check if any check mentions human review / oversight."""
    hint = (trace.get("remediation_hint") or "").lower()
    reason = (trace.get("reason") or "").lower()
    check = (trace.get("check_name") or "").lower()
    hitl_terms = ["human review", "human-in-the-loop", "oversight", "human approval", "hitl", "human check"]
    return any(t in hint or t in reason or t in check for t in hitl_terms)


def _build_remediation_markdown(audit: dict, traces: list[dict]) -> str:
    dataset = audit.get("dataset_name", "Unknown Dataset")
    audit_id = audit.get("id", "—")
    score = audit.get("overall_risk_score")

    lines = [
        "# SARO Remediation Report",
        "",
        f"**Audit:** {dataset}  ",
        f"**Audit ID:** `{audit_id}`  ",
        f"**Risk Score:** {f'{score:.1f}/100' if score is not None else '—'}  ",
        f"**Status:** {audit.get('status', '—').upper()}  ",
        "",
        "---",
        "",
        "## Remediation Actions",
        "",
    ]

    priority_order = {"fail": 0, "flagged": 1, "triggered": 2, "warn": 3}
    sorted_traces = sorted(traces, key=lambda t: priority_order.get(t.get("result", ""), 99))

    action_num = 1
    for t in sorted_traces:
        if t.get("is_remediated"):
            continue
        hint = t.get("remediation_hint") or "Review and address this finding."
        sentences = [s.strip() for s in hint.replace(". ", ".\n").split("\n") if s.strip()]
        lines.append(f"### Action {action_num}: {t.get('check_name', 'Finding')}")
        lines.append("")
        lines.append(f"- **Gate:** {t.get('gate_name', '')} (Gate {t.get('gate_id', '')})")
        lines.append(f"- **Severity:** {_severity_label(t.get('result', ''))} / {t.get('result', '').upper()}")
        lines.append(f"- **Effort:** {_effort_label(t.get('result', ''))}")
        lines.append(f"- **Finding:** {t.get('reason', '—')}")
        lines.append("")
        lines.append("**Numbered Fix Steps:**")
        for i, s in enumerate(sentences, 1):
            lines.append(f"{i}. {s}")
        lines.append("")
        action_num += 1

    lines.extend([
        "---",
        "",
        "*Generated by SARO — Smart AI Risk Orchestrator v2.2. "
        "All recommendations are evidence-based and traceable to matched rules.*",
    ])
    return "\n".join(lines)


def render(token: str) -> None:
    """Render the Remedy tab."""
    styles.apply()

    st.header("🔧 Remedy — Issue Tracker")
    st.caption(
        "Review all failed, warned, flagged, and triggered checks. "
        "Mark items as remediated once corrective action has been taken. "
        "All remediation events are immutably logged."
    )

    # ── Load completed audits ─────────────────────────────────────────────────
    try:
        audits: list[dict] = _get("/api/v1/audits?limit=100", token)
    except requests.ConnectionError:
        st.error(f"Cannot connect to SARO API at `{_API_BASE}`.")
        return
    except requests.HTTPError as e:
        st.error(f"Failed to load audits: {e}")
        return

    completed = [a for a in audits if a["status"] in ("completed", "failed")]
    if not completed:
        st.markdown(
            styles.empty_state(
                "🔧",
                "No audits to remediate",
                "Run an audit from the Upload & Scan tab. "
                "Completed audits with issues will appear here.",
            ),
            unsafe_allow_html=True,
        )
        return

    # ── Audit selector ─────────────────────────────────────────────────────────
    audit_options: dict[str, dict] = {
        f"{a.get('dataset_name') or 'Unnamed'} — {a['created_at'][:10]} [{a['status'].upper()}]": a
        for a in completed
    }
    selected_label = st.selectbox(
        "Select audit to remediate",
        list(audit_options.keys()),
        key="remedy_audit_select",
    )
    if not selected_label:
        return

    selected_audit = audit_options[selected_label]
    audit_id = selected_audit["id"]

    # ── Trace summary ─────────────────────────────────────────────────────────
    try:
        summary: dict = _get(f"/api/v1/traces/{audit_id}/summary", token)
    except requests.HTTPError as e:
        if e.response is not None and e.response.status_code == 404:
            st.info(
                "No trace data available for this audit. "
                "Traces are stored for audits run after the tracing update (v2.0+)."
            )
        else:
            st.error(f"Failed to load trace summary: {e}")
        return

    total = summary.get("total_traces", 0)
    issues = summary.get("total_failed", 0)
    remediated = summary.get("total_remediated", 0)
    pending = summary.get("pending_remediation", 0)

    # Progress bar
    if issues > 0:
        progress_pct = remediated / issues
        st.markdown(
            f'<div style="margin-bottom:8px">'
            f'<div style="font-size:0.78rem;font-weight:600;color:#64748b;'
            f'text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px">'
            f'Remediation Progress</div>'
            f'<div style="background:#1a2035;border-radius:4px;height:6px;overflow:hidden">'
            f'<div style="background:{"#10b981" if progress_pct >= 1 else "#3b82f6"};'
            f'width:{progress_pct*100:.0f}%;height:100%;transition:width 0.3s ease"></div>'
            f'</div>'
            f'<div style="font-size:0.78rem;color:#475569;margin-top:3px">'
            f'{remediated} of {issues} issue(s) resolved · {pending} pending'
            f'</div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Checks", total)
    col2.metric("Issues Found", issues)
    col3.metric("Remediated", remediated)
    col4.metric("Pending", pending)

    if pending == 0 and issues > 0:
        st.success("✅ All issues for this audit have been marked as remediated.")
    elif issues == 0:
        st.success("✅ No issues detected — all checks passed.")
        return

    st.divider()

    # ── Load failed traces ────────────────────────────────────────────────────
    show_remediated = st.toggle("Show already-remediated items", value=False, key="remedy_show_all")

    try:
        param = f"?include_remediated={'true' if show_remediated else 'false'}"
        traces: list[dict] = _get(f"/api/v1/traces/{audit_id}/failed{param}", token)
    except requests.HTTPError as e:
        st.error(f"Failed to load traces: {e}")
        return

    if not traces:
        st.info("No pending issues — all items have been remediated." if not show_remediated else "No failed traces found.")
        return

    # ── Export buttons ────────────────────────────────────────────────────────
    all_traces_for_export: list[dict] = traces
    md_content = _build_remediation_markdown(selected_audit, all_traces_for_export)
    export_json = json.dumps({"audit": selected_audit, "traces": traces}, indent=2, default=str)

    ec1, ec2, ec3 = st.columns([1, 1, 4])
    with ec1:
        st.download_button(
            "⬇ Export Markdown",
            data=md_content,
            file_name=f"saro_remediation_{str(audit_id)[:8]}.md",
            mime="text/markdown",
            use_container_width=True,
        )
    with ec2:
        st.download_button(
            "⬇ Export JSON",
            data=export_json,
            file_name=f"saro_remediation_{str(audit_id)[:8]}.json",
            mime="application/json",
            use_container_width=True,
        )

    st.divider()

    # ── HITL detection summary ─────────────────────────────────────────────────
    hitl_present_count = sum(1 for t in traces if _hitl_detected(t))
    hitl_missing_count = len([t for t in traces if not t.get("is_remediated")]) - hitl_present_count
    if hitl_missing_count > 0:
        st.markdown(styles.hitl_missing_banner(), unsafe_allow_html=True)

    # ── Group by gate ─────────────────────────────────────────────────────────
    by_gate: dict[str, list[dict]] = {}
    for t in traces:
        gate_key = f"Gate {t['gate_id']}: {t['gate_name']}"
        by_gate.setdefault(gate_key, []).append(t)

    # Priority sort within each gate
    priority_order = {"fail": 0, "flagged": 1, "triggered": 2, "warn": 3}

    result_icons = {
        "fail":      "❌",
        "warn":      "⚠️",
        "flagged":   "🚩",
        "triggered": "📋",
        "pass":      "✅",
    }
    result_colors = {
        "fail":      "#dc2626",
        "warn":      "#d97706",
        "flagged":   "#dc2626",
        "triggered": "#3b82f6",
        "pass":      "#10b981",
    }

    for gate_name, gate_traces in by_gate.items():
        gate_traces_sorted = sorted(gate_traces, key=lambda t: priority_order.get(t.get("result", ""), 99))
        pending_in_gate = sum(1 for t in gate_traces_sorted if not t["is_remediated"])

        st.subheader(
            f"{gate_name}  —  "
            f"{pending_in_gate} pending · {len(gate_traces_sorted)} total"
        )

        for trace in gate_traces_sorted:
            result = trace["result"]
            icon = result_icons.get(result, "•")
            color = result_colors.get(result, "#6b7280")
            is_rem = trace["is_remediated"]
            effort = _effort_label(result)
            severity = _severity_label(result)
            hitl = _hitl_detected(trace)

            remediated_badge = " ✅ Remediated" if is_rem else ""
            expander_label = (
                f"{icon} [{severity}] {trace['check_name'][:80]}{remediated_badge}"
            )

            with st.expander(expander_label, expanded=(not is_rem and result in ("fail", "flagged"))):
                # Metadata header
                st.markdown(
                    styles.meta_row(
                        Gate=f"{trace.get('gate_id')} — {trace.get('gate_name','')[:30]}",
                        Type=f"`{trace.get('check_type','')}`",
                        Result=result.upper(),
                        Effort=effort,
                    ),
                    unsafe_allow_html=True,
                )

                # HITL detection per item
                if not hitl and not is_rem:
                    st.markdown(
                        '<div class="saro-hitl-missing" style="font-size:0.8rem;padding:7px 12px">'
                        '⚠ No human-in-the-loop checkpoint detected for this finding.'
                        '</div>',
                        unsafe_allow_html=True,
                    )

                c1, c2 = st.columns([2, 1])
                with c1:
                    st.markdown("**Finding:**")
                    if result in ("fail", "flagged"):
                        st.markdown(
                            styles.deviation_callout(trace.get("reason") or "See detail below."),
                            unsafe_allow_html=True,
                        )
                    else:
                        st.write(trace.get("reason") or "—")

                    # Numbered remediation steps
                    hint = trace.get("remediation_hint") or ""
                    if hint:
                        st.markdown("**AI-Generated Fix Steps:**")
                        sentences = [s.strip() for s in hint.replace(". ", ".\n").split("\n") if s.strip()]
                        for i, sentence in enumerate(sentences, 1):
                            st.markdown(f"**{i}.** {sentence}")

                with c2:
                    # Effort pill
                    st.markdown(styles.effort_pill(effort), unsafe_allow_html=True)
                    st.markdown("")

                    if is_rem and trace.get("remediated_at"):
                        st.markdown(f"**Remediated:** {trace['remediated_at'][:19]}")

                # Raw detail
                if trace.get("detail_json"):
                    with st.expander("Raw detail data", expanded=False):
                        st.json(trace["detail_json"])

                # ── Remediate action ──────────────────────────────────────────
                if not is_rem:
                    st.divider()

                    # Copy remediation text
                    if hint:
                        sentences_copy = [s.strip() for s in hint.replace(". ", ".\n").split("\n") if s.strip()]
                        copy_text = (
                            f"Finding: {trace.get('reason','')}\n\n"
                            f"Remediation Steps:\n"
                            + "\n".join(f"{i}. {s}" for i, s in enumerate(sentences_copy, 1))
                        )
                        st.code(copy_text, language=None)

                    form_key = f"remedy_form_{trace['id']}"
                    with st.form(form_key):
                        notes = st.text_area(
                            "Remediation notes (optional)",
                            placeholder="Describe the corrective action taken — system prompt updated, guardrail added, etc.",
                            key=f"notes_{trace['id']}",
                            height=80,
                        )
                        ac1, ac2, ac3 = st.columns(3)
                        with ac1:
                            submitted = st.form_submit_button(
                                "✅ Mark as Remediated",
                                use_container_width=True,
                                type="primary",
                            )
                        with ac2:
                            # Jira export as download
                            jira_body = (
                                f"SARO Exception: {trace.get('check_name','')}\n\n"
                                f"Audit: {selected_audit.get('dataset_name','')}\n"
                                f"Audit ID: {audit_id}\n"
                                f"Severity: {severity}\n"
                                f"Finding: {trace.get('reason','')}\n\n"
                                f"Remediation:\n{hint}"
                            )
                            st.form_submit_button(
                                "📋 Export for Jira",
                                use_container_width=True,
                                disabled=False,
                                help="Download pre-filled Jira ticket content",
                            )
                        with ac3:
                            st.form_submit_button(
                                "📄 Export as Markdown",
                                use_container_width=True,
                                disabled=True,
                                help="Use the Export Markdown button above to export all issues",
                            )

                    if submitted:
                        try:
                            _post(
                                f"/api/v1/traces/{audit_id}/{trace['id']}/remediate",
                                token,
                                {"notes": notes or None},
                            )
                            st.success("✅ Marked as remediated.")
                            st.rerun()
                        except requests.HTTPError as e:
                            st.error(f"Failed to update: {e}")

        st.divider()
